-- Migration: Add AI Generated Items Support
-- Description: Adds table and columns for tracking AI-generated questions
-- Date: 2026-01-29

-- 1. Create ai_generated_items table for storing generation metadata
CREATE TABLE IF NOT EXISTS ai_generated_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Reference to the generated item (after it's saved)
    item_id VARCHAR(64) REFERENCES items(id) ON DELETE SET NULL,

    -- Reference to the source item used for generation
    source_item_id VARCHAR(64) NOT NULL,

    -- Generation parameters
    generation_model VARCHAR(50) NOT NULL,
    variation_type VARCHAR(20) NOT NULL,
    additional_prompt TEXT,

    -- Quality metrics
    confidence_score FLOAT,

    -- Approval workflow
    status VARCHAR(20) DEFAULT 'pending',  -- pending, approved, rejected
    approved_by VARCHAR(100),
    approved_at TIMESTAMPTZ,
    rejection_reason TEXT,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. Add AI generation columns to items table
ALTER TABLE items
ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT FALSE;

ALTER TABLE items
ADD COLUMN IF NOT EXISTS ai_metadata_id UUID REFERENCES ai_generated_items(id) ON DELETE SET NULL;

-- 3. Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_ai_generated_items_source
ON ai_generated_items(source_item_id);

CREATE INDEX IF NOT EXISTS idx_ai_generated_items_status
ON ai_generated_items(status);

CREATE INDEX IF NOT EXISTS idx_ai_generated_items_created
ON ai_generated_items(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_items_is_ai_generated
ON items(is_ai_generated) WHERE is_ai_generated = TRUE;

-- 4. Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_ai_generated_items_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_ai_generated_items_updated_at ON ai_generated_items;
CREATE TRIGGER trigger_ai_generated_items_updated_at
    BEFORE UPDATE ON ai_generated_items
    FOR EACH ROW
    EXECUTE FUNCTION update_ai_generated_items_updated_at();

-- 5. Add comments for documentation
COMMENT ON TABLE ai_generated_items IS 'Metadata for AI-generated question items';
COMMENT ON COLUMN ai_generated_items.item_id IS 'Reference to saved item (NULL if not yet saved)';
COMMENT ON COLUMN ai_generated_items.source_item_id IS 'ID of the original item used as generation source';
COMMENT ON COLUMN ai_generated_items.generation_model IS 'LLM model used (e.g., gpt-4o)';
COMMENT ON COLUMN ai_generated_items.variation_type IS 'Type of variation applied (numeric/context/structure/mixed)';
COMMENT ON COLUMN ai_generated_items.confidence_score IS 'Generation confidence score (0-1)';
COMMENT ON COLUMN ai_generated_items.status IS 'Approval status: pending, approved, rejected';
COMMENT ON COLUMN items.is_ai_generated IS 'Whether this item was generated by AI';
COMMENT ON COLUMN items.ai_metadata_id IS 'Reference to AI generation metadata';
